### ISSUE TITLE
Uh#1Tk#2Malvina : Actualizar documentación ESP32

### ISSUE THREAD

**Issue by CACHITO-13** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06#48]
## Actualizar en carpeta de Bibliografía los recursos del ESP32

**Comment by PROFMALVINA** [comment]
[ESP32_MANUAL.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06/files/11338360/ESP32_MANUAL.pdf)



[ESP 32.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06/files/11338362/ESP.32.pdf)



[PIN OUT ESP 32.docx](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06/files/11338363/PIN.OUT.ESP.32.docx)

**Comment by PROFMALVINA** [comment]
Javier , completé la tarea Actualizar documentación ESP32.

**Comment by CACHITO-13** [comment]
Hola Malvina, ¿cómo estás?
Te comento que los documentos no están relacionados con el proyecto (UPS - TTS056.pdf). Dejo una captura del mismo.
Además están alojados en main, debés moverlos a las carpetas correspondientes.
Saludos, Javier

**Comment by CACHITO-13** [comment]
![image](https://user-images.githubusercontent.com/86607494/234741669-9ec02d7f-021c-49cd-9315-8c2157498fb6.png)

**Comment by PROFMALVINA** [comment]
Javier tarea corregida.

**Comment by CACHITO-13** [comment]
Buenísimo, gracias Malvina! Buen trabajo.
