### ISSUE TITLE
Uh#1Tk#3Malvina : Actualizar Bibliotecas / Recursos

### ISSUE THREAD

**Issue by CACHITO-13** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06#49]

**Comment by PROFMALVINA** [comment]
[UPS - TTS056.pdf](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06/files/11338382/UPS.-.TTS056.pdf)

**Comment by CACHITO-13** [comment]
Hola Malvina, ¿cómo estás?
Te comento que los documentos no están relacionados con el proyecto (UPS - TTS056.pdf). Dejo una captura del mismo.
Además están alojados en main, debés moverlos a las carpetas correspondientes.
Los documentos no deberías subirlos en los Issues, sino al repositorio.
Saludos, Javier

**Comment by CACHITO-13** [comment]
![image](https://user-images.githubusercontent.com/86607494/234741636-dc11ab4f-3812-40f6-82a3-275ba1b86d36.png)

**Comment by PROFMALVINA** [comment]
Javier, corregí lo que me solicitaste.

**Comment by CACHITO-13** [comment]
Buenísimo, gracias Malvina! Buen trabajo.
