### ISSUE TITLE
Uh#1Tk#2Malvina: Mover los documentos subidos en main a las carpetas correspondientes

### ISSUE THREAD

**Issue by CACHITO-13** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-06#51]
# Tarea designada por Scrum master

1. Comprobar la utilidad de los docuentos subidos al repositorio y filtrar los que no aportan al trabajo cooperativo (**NO SUBIR DOCUMENTOS AJENOS AL PROYECTO**)
2. Mover los documentos ya filtrados de **main** a las carpetas correspondientes (B_Bibliografía o C_Ampliación)
3. Asegurarse de dar el uso correcto a las **Issues** del proyecto, teniendo en claro el objetivo de las mismas en el proyecto.

**Comment by PROFMALVINA** [comment]
Javier, documentos movidos.

**Comment by CACHITO-13** [comment]
Malvina por favor asignate esta Issue acá o en el tablero Kanban y quedaría lista. 
¡Muchas gracias!

**Comment by PROFMALVINA** [comment]
Javier, tarea corregida.

**Comment by CACHITO-13** [comment]
Buenísimo Malvina. Cierro la Issue como completada. ¡Muchas gracias!

![image](https://user-images.githubusercontent.com/86607494/235398062-f3efbc4d-fb6a-443a-955b-68dfdb8bc63a.png)

**Comment by PROFMALVINA** [comment]
Gracias a vos, Javier.
